services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: avito_test2.0
      POSTGRES_PASSWORD: 7049
      POSTGRES_DB: avito_test2.0
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: avito_test2.0
      DB_PASSWORD: 7049
      DB_NAME: avito_test2.0
      JWT_SECRET: your_jwt_secret

volumes:
  postgres_data: